#######################################
### Dockerfile with a Scratch Image ###
#######################################

FROM scratch

COPY simple-app ./

EXPOSE 8080

CMD [ "/simple-app" ]


#######################################
### Dockerfile with a Alpine Image  ###
#######################################

# FROM golang:alpine

# RUN mkdir /app
# ADD ./simple-app /app
# WORKDIR /app

# EXPOSE 8080

# CMD [ "/app/simple-app" ]
