version: 0.2

phases:
  install:
    commands:
      - go get github.com/gorilla/mux
  build:
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./docker/simple-app ./go/main.go

artifacts:
  type : zip
  files:
    - docker/*
  base-directory : 'docker'
