version: 0.2

phases:
  install:
    commands:
      - echo download and install go dependencies...
      - go get github.com/gorilla/mux
  build:
    commands:
      - echo Build started on `date`
      - echo Building the go app...
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./docker/simple-app ./go/main.go

artifacts:
  files:
    - docker/*
  discard-paths: yes
#  base-directory: docker
