version: 0.2

phases:
  install:
    commands:
      - go get github.com/gorilla/mux
  build:
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o simple-app ./main.go

artifacts:
  files:
    - simple-app
    - docker/Dockerfile
    - docker/buildspec-docker.yml
